[package]
edition = "2021"
name = "eun"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
polars = { version = "0.40.0", features = [
    "dtype-array",
    "lazy",
    "list_eval",
    "round_series",
    "serde",
] }
